import 'package:flutter/material.dart';

class CourseModel {
  final String id;
  final String name;
  final String description;
  final String simpleExplanation;
  final String admissionProcess;
  final String studyMaterials;
  final String duration;
  final String category;
  final String badge;
  final IconData icon;
  final Color accentColor;
  final Color containerColor;
  final List<String> keywords;

  const CourseModel({
    required this.id,
    required this.name,
    required this.description,
    required this.simpleExplanation,
    required this.admissionProcess,
    required this.studyMaterials,
    required this.duration,
    required this.category,
    required this.badge,
    required this.icon,
    required this.accentColor,
    required this.containerColor,
    this.keywords = const [],
  });
}

final List<CourseModel> allCourses = [
  const CourseModel(
    id: 'mscit',
    name: "MKCL'S MSCIT",
    description: "Maharashtra State Certificate in Information Technology. Essential computer skills for academic and professional success.",
    simpleExplanation: "This is a basic computer course that everyone should do. You will learn how to use a computer, the internet, and basic office work. It's the most famous certificate in Maharashtra!",
    admissionProcess: "Visit our center with your Aadhaar card and 2 photos. You can pay the fee in one go or installments.",
    studyMaterials: "You will get a colorful MKCL textbook and access to the 'ERA' learning software on our computers.",
    duration: "6 Months",
    category: "Certified Programs",
    badge: "Premium",
    icon: Icons.verified_outlined,
    accentColor: Color(0xFFFFE04A),
    containerColor: Color(0xFF665200),
    keywords: ['mscit', 'ms-cit', 'basic', 'certificate', 'computer start'],
  ),
  const CourseModel(
    id: 'hardware',
    name: "Diploma in IT Hardware & Networking",
    description: "Comprehensive training in PC assembly, troubleshooting, server management, and network infrastructure.",
    simpleExplanation: "In this course, you learn how to open a computer, fix it when it breaks, and connect many computers together in an office. You will become a 'Computer Doctor'!",
    admissionProcess: "Direct admission at center. Minimum 10th pass recommended.",
    studyMaterials: "Hands-on tools, old and new CPUs for practice, and a printed lab manual.",
    duration: "1 Year",
    category: "Hardware & Networking",
    badge: "Practical",
    icon: Icons.settings_input_component_outlined,
    accentColor: Color(0xFF00FFCC),
    containerColor: Color(0xFF004D3D),
    keywords: ['hardware', 'repair', 'networking', 'cpu', 'fixing', 'parts'],
  ),
  const CourseModel(
    id: 'web',
    name: "Web Designing & Web Development",
    description: "Build dynamic, responsive websites using HTML, CSS, JavaScript, and modern development frameworks.",
    simpleExplanation: "Learn how to make websites like the ones you use every day. You'll learn to write code that makes things look pretty and work on the internet.",
    admissionProcess: "Join anytime! No prior coding knowledge needed. Come to the center for a demo.",
    studyMaterials: "Access to our coding server, PDF notes, and project templates.",
    duration: "4 Months",
    category: "Programming",
    badge: "In Demand",
    icon: Icons.code_outlined,
    accentColor: Color(0xFFFF2D78),
    containerColor: Color(0xFFB3004E),
    keywords: ['web', 'website', 'html', 'css', 'javascript', 'coding', 'internet'],
  ),
  const CourseModel(
    id: 'graphic',
    name: "Graphic Designing",
    description: "Master industry-standard tools like Photoshop and Illustrator for visual communication and branding.",
    simpleExplanation: "Learn to make beautiful posters, logos, and photos. You will use the same tools that professionals use for movies and ads!",
    admissionProcess: "Bring your creative mind and a valid ID. We'll set you up with a system.",
    studyMaterials: "Huge library of design assets, fonts, and step-by-step video tutorials.",
    duration: "4 Months",
    category: "Design & Creative",
    badge: "Creative",
    icon: Icons.palette_outlined,
    accentColor: Color(0xFFFF2D78),
    containerColor: Color(0xFFB3004E),
    keywords: ['graphic', 'design', 'photoshop', 'logo', 'poster', 'creative'],
  ),
  const CourseModel(
    id: 'uiux',
    name: "UI UX Designing",
    description: "Design beautiful interfaces and user-centric experiences. Master wireframing and prototyping.",
    simpleExplanation: "Learn how to design how apps (like WhatsApp or Instagram) should look and feel so they are easy for everyone to use.",
    admissionProcess: "Portfolio-based guidance provided. Visit us to see student projects.",
    studyMaterials: "Figma design kits and user research templates.",
    duration: "1 Year",
    category: "Design & Creative",
    badge: "Trending",
    icon: Icons.draw_outlined,
    accentColor: Color(0xFF00FFCC),
    containerColor: Color(0xFF004D3D),
    keywords: ['ui', 'ux', 'app design', 'figma', 'interface'],
  ),
  const CourseModel(
    id: 'basics',
    name: "Basics of Computer",
    description: "Fundamental computer operations, OS usage, and essential internet navigation skills for beginners.",
    simpleExplanation: "For absolute beginners. We teach you how to turn on a computer, use a mouse, type, and search things on Google safely.",
    admissionProcess: "Just walk in! We have special batches for elders and kids.",
    studyMaterials: "Simple pictorial guide and practice sheets.",
    duration: "2 Months",
    category: "Fundamentals",
    badge: "Beginner",
    icon: Icons.computer_outlined,
    accentColor: Color(0xFFFFE04A),
    containerColor: Color(0xFF665200),
    keywords: ['basics', 'computer start', 'mouse', 'keyboard', 'internet search'],
  ),
  const CourseModel(
    id: 'fundamentals',
    name: "Computer Fundamentals",
    description: "Deep dive into computer architecture, system software, and core IT concepts.",
    simpleExplanation: "Learn the 'science' behind computers. How they think, how they store data, and how software works inside.",
    admissionProcess: "Recommended for students wanting to pursue IT careers. Registration at center.",
    studyMaterials: "Theory booklets and hardware diagrams.",
    duration: "6 Months",
    category: "Fundamentals",
    badge: "Essential",
    icon: Icons.desktop_windows_outlined,
    accentColor: Color(0xFFFF2D78),
    containerColor: Color(0xFFB3004E),
    keywords: ['fundamentals', 'it', 'software', 'how computer works'],
  ),
  const CourseModel(
    id: 'office',
    name: "Office Automation",
    description: "Master MS Word, Excel, PowerPoint, and modern office tools for workplace productivity.",
    simpleExplanation: "Learn how to type letters in Word, make bills in Excel, and create beautiful presentations in PowerPoint. Essential for any office job!",
    admissionProcess: "Open to all. Just bring your ID proof to the office.",
    studyMaterials: "Step-by-step Excel guides and practice files for Word and PPT.",
    duration: "1 Year",
    category: "Office Automation",
    badge: "Corporate",
    icon: Icons.table_chart_outlined,
    accentColor: Color(0xFF00FFCC),
    containerColor: Color(0xFF004D3D),
    keywords: ['office', 'word', 'excel', 'powerpoint', 'typing letters', 'bills', 'ms office'],
  ),
  const CourseModel(
    id: 'tally',
    name: "Financial accounting with Tally ERP",
    description: "Advanced accounting, inventory management, and financial reporting with GST filing.",
    simpleExplanation: "This course teaches you how to manage shop or company accounts on a computer. You will learn about GST, profit/loss, and how to keep record of money.",
    admissionProcess: "Commerce students or anyone interested in accounts can join. Visit center for form.",
    studyMaterials: "Tally practice company data and GST reference book.",
    duration: "6 Months",
    category: "Finance",
    badge: "Skill Based",
    icon: Icons.account_balance_outlined,
    accentColor: Color(0xFFFFE04A),
    containerColor: Color(0xFF665200),
    keywords: ['tally', 'accounts', 'gst', 'money', 'business', 'accounting'],
  ),
  const CourseModel(
    id: 'marathi_typing',
    name: "Marathi Typing with advance Methods and AI",
    description: "Master touch typing in Marathi using AI-driven methods for high speed and accuracy.",
    simpleExplanation: "Learn how to type in Marathi very fast without looking at the keyboard. We use special AI tools to help you learn faster for government exams.",
    admissionProcess: "Simple registration at front desk.",
    studyMaterials: "Marathi keyboard charts and AI-based typing software access.",
    duration: "6 Months",
    category: "Typing",
    badge: "Essential",
    icon: Icons.keyboard_outlined,
    accentColor: Color(0xFFFF2D78),
    containerColor: Color(0xFFB3004E),
    keywords: ['marathi typing', 'typing', 'government job', 'exam'],
  ),
  const CourseModel(
    id: 'eng_hin_typing',
    name: "English and Hindi Typing with Advance methods and AI",
    description: "High-speed English and Hindi typing training with advanced AI techniques.",
    simpleExplanation: "Boost your typing speed in English and Hindi. Great for office work and data entry jobs.",
    admissionProcess: "Walk-in admission. Flexible batch timings.",
    studyMaterials: "Typing speed tracker and multi-language keyboard guides.",
    duration: "6 Months",
    category: "Typing",
    badge: "Essential",
    icon: Icons.keyboard_outlined,
    accentColor: Color(0xFF00FFCC),
    containerColor: Color(0xFF004D3D),
    keywords: ['english typing', 'hindi typing', 'speed', 'data entry'],
  ),
  const CourseModel(
    id: 'prog_basic',
    name: "Basics of C, C++, C#, JAVA, Python, Kotlin Programming",
    description: "Build a strong foundation in core programming concepts across multiple essential languages.",
    simpleExplanation: "Start your journey to becoming a software developer. Learn the basic languages used to build apps and software.",
    admissionProcess: "No prior knowledge needed. We start from zero! Visit center to enroll.",
    studyMaterials: "Code notebooks, practice exercises, and software compilers.",
    duration: "1 Year",
    category: "Programming",
    badge: "Foundation",
    icon: Icons.terminal_outlined,
    accentColor: Color(0xFFFFE04A),
    containerColor: Color(0xFF665200),
    keywords: ['programming', 'coding', 'java', 'python', 'c++', 'software'],
  ),
  const CourseModel(
    id: 'prog_adv',
    name: "Advance in C, C++, C#, JAVA, Python, Kotlin Programming",
    description: "Master advanced programming techniques, data structures, and enterprise software development.",
    simpleExplanation: "Take your coding skills to the next level. Learn how to build complex apps and solve hard problems like a pro.",
    admissionProcess: "Basic programming knowledge required. Interview with instructor recommended.",
    studyMaterials: "Advanced project source codes and interview preparation guide.",
    duration: "2 Years",
    category: "Programming",
    badge: "Advanced",
    icon: Icons.integration_instructions_outlined,
    accentColor: Color(0xFFFF2D78),
    containerColor: Color(0xFFB3004E),
    keywords: ['advanced programming', 'expert coding', 'data structures'],
  ),
  const CourseModel(
    id: 'ai',
    name: "Prompt Engineering and Generative AI",
    description: "Master LLMs and generative AI tools to automate workflows and enhance productivity.",
    simpleExplanation: "Learn how to talk to AI like ChatGPT to do your work in seconds. You will learn to make images, write emails, and use AI to save hours of time!",
    admissionProcess: "Basic computer knowledge required. Contact coordinator for seat.",
    studyMaterials: "List of 500+ useful AI prompts and guide to top AI tools.",
    duration: "1 Year",
    category: "AI & Future Skills",
    badge: "Future Ready",
    icon: Icons.psychology_outlined,
    accentColor: Color(0xFF00FFCC),
    containerColor: Color(0xFF004D3D),
    keywords: ['ai', 'chatgpt', 'generative ai', 'prompt', 'future'],
  ),
  const CourseModel(
    id: 'marketing',
    name: "Digital Marketing with AI",
    description: "Dominate SEO, SMM, and content strategy utilizing cutting-edge AI-powered marketing tools.",
    simpleExplanation: "Learn how to sell products and grow businesses on Facebook, Instagram, and Google using the power of AI.",
    admissionProcess: "Open for students, business owners, and creators. Visit us for a free session.",
    studyMaterials: "Social media marketing checklist and AI marketing tools guide.",
    duration: "5 Months",
    category: "AI & Future Skills",
    badge: "Strategy",
    icon: Icons.trending_up_outlined,
    accentColor: Color(0xFFFFE04A),
    containerColor: Color(0xFF665200),
    keywords: ['marketing', 'digital', 'ads', 'instagram', 'facebook', 'sell online'],
  ),
];

const List<String> courseCategories = [
  'All Programs',
  'Certified Programs',
  'Programming',
  'AI & Future Skills',
  'Design & Creative',
  'Hardware & Networking',
  'Finance',
  'Typing',
  'Fundamentals',
  'Office Automation',
];
